chess_dbt:
  target: prod
  outputs:
    prod:
      type: duckdb
      path: data/chess.duckdb
      threads: 4
      module_paths:
        - /mount/src/chess_streamlit/src/chess_dbt/lib
      plugins:
        # Custom module in the lib directory that defines SQL UDFs written in Python at the start of
        # the dbt run
        - module: my_custom_functions